### ISSUE TITLE
Did anyone experience a CUDA out of memory during Training ?

### ISSUE THREAD

**Issue by YacineDeghaies** [isl-org/ZoeDepth#130]
I set the batch size to 1 and it didn't solve the problem. Any help would be appreciated.

the server am using has 4 x Nvidia RTX A6000

![Screenshot 2024-08-02 at 23 09 18 (2)](https://github.com/user-attachments/assets/24f43aa0-94e2-48cc-85e4-7331179d8b57)

**Comment by SheepDoctor** [comment]
set **"use_amp": True** in config.py, this works for me.

**Comment by michaeltan53** [comment]
the way of "set "use_amp": True" does not work for me, does it mean that my gpu was indeed out of memory?

**Comment by YacineDeghaies** [comment]
> the way of "set "use_amp": True" does not work for me, does it mean that my gpu was indeed out of memory?

Yes, I tried on a better GPU and it worked.
